package com.lankawings.servlet;

import com.lankawings.dao.BookingDAO;
import com.lankawings.model.Booking;
import jakarta.servlet.annotation.WebServlet;
import jakarta.servlet.http.*;
import java.io.IOException;
import java.io.PrintWriter;
import java.text.SimpleDateFormat;

@WebServlet("/ticket/download")
public class TicketDownloadServlet extends HttpServlet {
    protected void doGet(HttpServletRequest r,HttpServletResponse s)throws IOException{
        try{
            Booking b=new BookingDAO().find(Integer.parseInt(r.getParameter("bookingId")));
            if(b==null){ s.sendError(404,"Booking not found"); return; }
            String safe=b.getPnr().replaceAll("[^A-Za-z0-9_-]","");
            s.setContentType("text/html;charset=UTF-8");
            s.setHeader("Content-Disposition","attachment; filename=LankaWings_E-Ticket_"+safe+".html");
            SimpleDateFormat df=new SimpleDateFormat("dd MMM yyyy, HH:mm");
            PrintWriter out=s.getWriter();
            out.println("<!doctype html><html><head><meta charset='UTF-8'><title>Lanka Wings E-Ticket</title><style>body{font-family:Arial,sans-serif;margin:40px;color:#13223d}.ticket{max-width:760px;margin:auto;border:2px solid #13223d;border-radius:18px;overflow:hidden}.head{background:#13223d;color:#fff;padding:24px;font-size:24px;font-weight:bold}.body{padding:28px}.route{font-size:26px;font-weight:bold;margin:12px 0 28px}.grid{display:grid;grid-template-columns:1fr 1fr;gap:18px}.grid small{display:block;color:#667085}.foot{margin-top:28px;padding-top:18px;border-top:1px dashed #aaa}</style></head><body><div class='ticket'><div class='head'>Lanka Wings — Electronic Ticket</div><div class='body'>");
            out.println("<div class='route'>"+esc(b.getOrigin())+" &nbsp; ✈ &nbsp; "+esc(b.getDestination())+"</div><div class='grid'>");
            field(out,"Passenger",b.getPassengerName()); field(out,"PNR",b.getPnr()); field(out,"Flight",b.getFlightNo()); field(out,"Seat",b.getSeatNumber()); field(out,"Departure",df.format(b.getDepartureTime())); field(out,"Status",b.getBookingStatus());
            out.println("</div><div class='foot'>Generated by Lanka Wings Booking Management</div></div></div></body></html>");
        }catch(Exception e){ s.sendError(500,e.getMessage()); }
    }
    private void field(PrintWriter out,String label,String value){ out.println("<div><small>"+label+"</small><b>"+esc(value)+"</b></div>"); }
    private String esc(String s){ if(s==null)return "";return s.replace("&","&amp;").replace("<","&lt;").replace(">","&gt;").replace("\"","&quot;"); }
}
