IF DB_ID('LankaWingsTicketReservationDB') IS NULL
BEGIN
    CREATE DATABASE LankaWingsTicketReservationDB;
END;
GO
USE LankaWingsTicketReservationDB;
GO
IF OBJECT_ID('dbo.Bookings','U') IS NOT NULL DROP TABLE dbo.Bookings;
IF OBJECT_ID('dbo.Flights','U') IS NOT NULL DROP TABLE dbo.Flights;
GO
CREATE TABLE Flights (
    FlightID INT IDENTITY(1,1) PRIMARY KEY,
    FlightNo VARCHAR(15) NOT NULL UNIQUE,
    Origin VARCHAR(80) NOT NULL,
    Destination VARCHAR(80) NOT NULL,
    DepartureTime DATETIME2 NOT NULL,
    ArrivalTime DATETIME2 NOT NULL,
    Fare DECIMAL(10,2) NOT NULL CHECK (Fare >= 0),
    TotalSeats INT NOT NULL DEFAULT 72 CHECK (TotalSeats > 0),
    Status VARCHAR(20) NOT NULL DEFAULT 'SCHEDULED' CHECK (Status IN ('SCHEDULED','BOARDING','DELAYED','CANCELLED','COMPLETED')),
    Aircraft VARCHAR(80) NOT NULL DEFAULT 'Airbus A320'
);
CREATE TABLE Bookings (
    BookingID INT IDENTITY(1,1) PRIMARY KEY,
    PNR VARCHAR(20) NOT NULL UNIQUE,
    FlightID INT NOT NULL,
    PassengerName VARCHAR(120) NOT NULL,
    PassportNo VARCHAR(40) NOT NULL,
    SeatNumber VARCHAR(8) NOT NULL,
    BookingStatus VARCHAR(20) NOT NULL DEFAULT 'CONFIRMED' CHECK (BookingStatus IN ('CONFIRMED','CANCELLED')),
    BookedAt DATETIME2 NOT NULL DEFAULT SYSDATETIME(),
    CONSTRAINT FK_Bookings_Flights FOREIGN KEY (FlightID) REFERENCES Flights(FlightID)
);
GO
CREATE UNIQUE INDEX UX_Bookings_ActiveSeat ON Bookings(FlightID,SeatNumber) WHERE BookingStatus <> 'CANCELLED';
GO
INSERT INTO Flights (FlightNo,Origin,Destination,DepartureTime,ArrivalTime,Fare,TotalSeats,Status,Aircraft) VALUES
('LW101','Colombo (CMB)','Dubai (DXB)',DATEADD(DAY,3,SYSDATETIME()),DATEADD(HOUR,8,DATEADD(DAY,3,SYSDATETIME())),78500.00,72,'SCHEDULED','Airbus A320neo'),
('LW204','Colombo (CMB)','Doha (DOH)',DATEADD(DAY,5,SYSDATETIME()),DATEADD(HOUR,7,DATEADD(DAY,5,SYSDATETIME())),69900.00,72,'SCHEDULED','Airbus A320'),
('LW330','Colombo (CMB)','Singapore (SIN)',DATEADD(DAY,8,SYSDATETIME()),DATEADD(HOUR,5,DATEADD(DAY,8,SYSDATETIME())),92500.00,84,'SCHEDULED','Airbus A321'),
('LW415','Colombo (CMB)','Kuala Lumpur (KUL)',DATEADD(DAY,10,SYSDATETIME()),DATEADD(HOUR,4,DATEADD(DAY,10,SYSDATETIME())),64800.00,72,'SCHEDULED','Airbus A320neo'),
('LW520','Colombo (CMB)','Malé (MLE)',DATEADD(DAY,2,SYSDATETIME()),DATEADD(HOUR,2,DATEADD(DAY,2,SYSDATETIME())),45500.00,60,'SCHEDULED','ATR 72-600');
GO
